os: linux

dist: xenial

sudo: required

git:
  depth: 3

addons:
  apt:
    update:
    - true

before_install:
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/toolchain/
  - sudo chmod -R a+x ~/toolchain/*

install: true

matrix:
  include:
    - name: "Built for gnsz6735_66_n_defconfig"
      env: DEFCONFIG=gnsz6735_66_n_defconfig
    - name: "Built for gnsz6735m_65_n_defconfig"
      env: DEFCONFIG=gnsz6735m_65_n_defconfig
    - name: "Built for gnsz6737m_65_n_defconfig"
      env: DEFCONFIG=gnsz6737m_65_n_defconfig
    - name: "Built for gnsz6737t_66_n_defconfig"
      env: DEFCONFIG=gnsz6737t_66_n_defconfig
    - name: "Built for gnsz6753_66_n_defconfig"
      env: DEFCONFIG=gnsz6753_66_n_defconfig

script:
  - mkdir out
  - make O=out clean
  - make O=out mrproper
  - export CROSS_COMPILE=~/toolchain/bin/aarch64-linux-android-
  - export ARCH=arm64 
  - export KBUILD_BUILD_USER="fr3aky"
  - export KBUILD_BUILD_HOST="Phantom_Zone"
  - export ARCH_MTK_PLATFORM=mt6735
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE $DEFCONFIG
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j32
  - KERNEL_DIR=$PWD
  - cp $KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb $KERNEL_DIR/out/arch/arm64/boot/$DEFCONFIG-n_zImage
  - ZIMAGE=$KERNEL_DIR/out/arch/arm64/boot/$DEFCONFIG-n_zImage

after_success:
  - curl --upload-file $ZIMAGE https://transfer.sh/ && echo ""

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HjAdnP44pVoLXRivJf5d/4DXxeWCM+hI9IOTg0+cmjkecjzkr1vexKgMEAtSmeh7KYZjwJhocgXIAVkpvhFsXEao4rxIJCBSimEVUYdH00pPdPU+xk+sSybb++aqxxN8obN0dxXVO9iskvaIRGIrVVsST3SflJX0BaHcaO5YeWaIZ8dxaiOH3dWtqou6iH9wRJILh4RXKMhYc2Dl+WBlNrCgLJwbc8W1Tm0OtHCjDRAeJtF1a/ABKd8IUqmDAcmwpj19JZsEvXHWnXoSU+fffneJxMAfeB5t34do8QHjhbjzUvtq1xAMhA947aXXcIgO3ylTmpfcdoJaV83xWeEZuA9mm/AAoyuC3Sq0Ox2JaGE/AdYr1or+9Kmf7fgevnRffI/xOMjE4h4y90M2sEIl3wvnhza4/IEda63qsSIUB9ez2hPf8pBUW54RkXWU9D3DpoefSPGRUqOfpsJ822lcsSjL9ce5bOCNJfsj5Puoo5IKOK9GuQnQTlQCTstBd8jJhKZxKR8VNCDW4ILut7OdaaAHi52DjazftchpME2GfPo0KrdUT/81e/COfIhlWHYMkhA5WtGTUApnOaukc6S42VgduoVgsn4A9lOKzCLAkJa7yI+8KgeY3q4WS81jL2IlLIOllb+qwHR+MdtLyfUPJS1PTNdueswa8VQ5rx9CvnU=
  file: $ZIMAGE
  on:
    tags: false
    repo: PhantomZone54/a8-update
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
